# by wf
sourceDir = "~/omd_dotF"
[git]
    #  导致 chezmoi: fork/exec /usr/bin/git: argument list too long
    # autoPush = true
[diff]
    command = "delta"
    pager = "nvim"
    args = ["{{ .Destination }}", "{{ .Target }}"]  # 默认的

